datasets: [nlp4lp_test, nl4opt_test, industryor_test, logior, optibench, optmath_bench]
data_path_template: ./data/optimization_tasks/split/test_data/${dataset}.json

library_path: ./data/experience_library/original_gpt4o_gurobi_library.json
taxonomy_path: ./data/experience_library/original_gpt4o_gurobi_taxonomy.json

output_folder_template: ${dataset}_eval_gpt54_e1_original
model: gpt-5.4
service: azure

n_runs: 3
temperature: 0.0
pass_at_k: 1

ablation:
  taxonomy: true
  rewrite: false
  include_example: true
  include_program_insight: true
  max_debug_retry: 5

  sweep_one_by_one: false
  sweep_params: [include_example]
  include_base: false
