base_model: gpt-5.4
advanced_model: gpt-5.4
base_service: azure
advanced_service: azure
verbose: false
start_iter: 0
data_slice:

api_keys:
  OPEN_ROUTER_KEY:
  GEMINI_API_KEY:
  OPENAI_API_KEY:

params:
  num_iterations: 1
  batch_size: 12
  tolerance: 1e-6
  max_solution_attempts: 1
  max_verify_attempts: 3
  variant_num: 5

dataset: train_data_all_452
output_folder: e2_gpt54_gurobi_train_data_all_452
file_paths:
  train_data_path: ./data/optimization_tasks/train/${dataset}.json
  train_output_dir: ./learning/${output_folder}/
  lib_dir: ./data/experience_library/iterations/${output_folder}/
  metrics_log_path: ./learning/${output_folder}/iteration_metrics.json

ablation:
  taxonomy: true
  rewrite: false
  include_example: true
  include_program_insight: true
  max_debug_retry: 3

pricing:
  gemini:
    gemini-2.5-pro:
      prompt_per_million: 1.25
      completion_per_million: 10.0
    gemini-2.5-flash:
      prompt_per_million: 0.30
      completion_per_million: 2.50

  openai:
    gpt-4o:
      prompt_per_million: 2.50
      completion_per_million: 10.0
    gpt-4o-mini:
      prompt_per_million: 0.15
      completion_per_million: 0.60
    gpt-4.1:
      prompt_per_million: 2.00
      completion_per_million: 8.00
    gpt-5.2:
      prompt_per_million: 0.00
      completion_per_million: 0.00
    gpt-5.4:
      prompt_per_million: 0.00
      completion_per_million: 0.00
